drop table if exists "user" cascade;

create table "user"
(
    id bigint generated by default as identity,
    login_id varchar(15),
    password varchar(255),
    name varchar(10),
    role varchar(15),
    tapology_url varchar(255),
    sherdog_url varchar(255),
    primary key (id)
)