server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/seojeongseop/desktop/project/git-local-repo
          uri: https://github.com/seo92js/msa-martial-arts-community
          search-paths:
            - 'git-local-repo'